language: python
matrix:
  include:
  - sudo: required
    services:
    - docker
    env:
    - PIP=pip
    - CIBW_MANYLINUX1_X86_64_IMAGE=safijari/manylinux-x64
    - CIBW_PLATFORM=linux
    - CIBW_SKIP="*-manylinux1_i686"
    - CIBW_ENVIRONMENT_LINUX="COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG"
    - CIBW_BEFORE="pip install pybind11"
install:
- "$PIP install cibuildwheel==0.10.0"
script:
- cibuildwheel --output-dir wheelhouse
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: YsxEt9u0Pfd37Crz9qF5FZBzPW46beRk2G5rZGQILU2kxjMaHpjQiC6m2Jo7l+ybmYhTaEUP4heAZ1rbCGq9qWTrdKNRXZf96Wn2++xDg3RPiNRwgiMRL1UWLQZz3B8WQ+lB0D+jY7qLPToga5FuYcxhWq0q9bKtsQLdJfodqOcp5qFN0R/JUekmr5gmr4GFtOI6JQFHQhMjNDc+hz7ALnXITytrAhgUxlFG3IOIxXU/pgXxo+Mf8UW9hEJEwakLpBmVwZuksu3mdULJgI6Ug9aAkjPz/BYOf1K9WO4a3pIAsPZoPPPec+DNtQ+8EwDT0oL/msZjrhGS/vK2Ig2RK3WLILcBHWYnxD47aIwqeO3PiHBKsdz2KQhiLKsaFMVbuH/lPY/60bdK+cEQW6axIxOIo0bAiT7ZzqT1FFF+KE3NTA++yROiem5/BTWk3gJQ8ANF3YOgdvvzQhP0nqbIs72ppbQWi43Ra7RJDxzvZIQdkOdK9DhTnYvdisdlXIHsZolutFCtNG4Fh+3Dalfa12rlREL77zgum9NU1VbBkOYCdbXNPNJAvHKk+6F3e5QoEq8KQKuBp3AOqbiaPFXg3hP4nYxErEXgNFjsUvAIuuq41dC6RLhMD3bbNeiBZGeI2/aSzXPca6Ifru+U097A4lQbMg64RxF9xTTlQYwI+xQ=
  file: wheelhouse/*
  file_glob: true
  on:
    repo: safijari/open_karto
    branch: python-devel
